### ISSUE TITLE
Changing sliders makes Protohax crash

### ISSUE THREAD

**Issue by NewVibey** [hax0r31337/ProtoHax-Android#16]
Everytime I changed the sliders, it crashes every time.
It maybe is because I am using the Pre-release version and hope you'll take it as a bug report I guess.

**Comment by hax0r31337** [comment]
First of all, thanks for the report.  

And this bug has already fixed in https://github.com/hax0r31337/ProtoHax/commit/b125d1a9816cb4c0432b7d9d68890444d355329f, please wait patience till next release :)
