### ISSUE TITLE
求求你不要再做外挂了

### ISSUE THREAD

**Issue by szzz666** [hax0r31337/ProtoHax-Android#24]
求求你不要再做外挂了求求你不要再做外挂了求求你不要再做外挂了求求你不要再做外挂了求求你不要再做外挂了求求你不要再做外挂了求求你不要再做外挂了求求你不要再做外挂了

 >   recovered deleted issue body

**Comment by hax0r31337** [comment]
Please describe the problem you've faced in English, this is a **English only repository** and I'm unable to read the language which you're using

**Comment by szzz666** [comment]
Please don't make cheating software anymore

**Comment by hax0r31337** [comment]
> szzz666(deleted): Please don't make cheating software anymore

why

**Comment by szzz666** [comment]
Because your cheating software can be used within the server, causing an unfair situation, many normal players have abandoned the game as a result. Your software has spread widely in China, and some children under the age of 18 use your software to disrupt others' gaming experience

**Comment by hax0r31337** [comment]
> szzz666(deleted): Because your cheating software can be used within the server, causing an unfair situation, many normal players have abandoned the game as a result. Your software has spread widely in China, and some children under the age of 18 use your software to disrupt others' gaming experience

if your server was fucked up by one of users of ProtoHax, then improve your damn anticheat or shut down your server

**Comment by hax0r31337** [comment]
> szzz666(deleted): More Stars in Anti Cheating Software 
https://github.com/Physical-Science-Academy/NoCheatPlus

Ok, then what?

**Comment by hax0r31337** [comment]
> szzz666(deleted): Join anti cheating

nah grief servers is fun I'm not giving it up

**Comment by szzz666** [comment]
You are an excellent developer

**Comment by hax0r31337** [comment]
> szzz666(deleted): You are an excellent developer

Thanks

**Comment by hax0r31337** [comment]
Thanks for [your issue](https://github.com/Physical-Science-Academy/NoCheatPlus/issues/71), I decided to stepping forward by adding anticheat bypasses to my cheat

**Comment by szzz666** [comment]
![CAE8BC2557F9FE2FAF929718663872BF](https://github.com/hax0r31337/ProtoHax-Android/assets/60167194/fe4e8e14-4c15-4655-82e0-66cebde0d5ea)

**Comment by szzz666** [comment]
Your project is being sold by others

**Comment by hax0r31337** [comment]
> szzz666(deleted): ![CAE8BC2557F9FE2FAF929718663872BF](https://github.com/hax0r31337/ProtoHax-Android/assets/60167194/fe4e8e14-4c15-4655-82e0-66cebde0d5ea) 
> szzz666(deleted): Your project is being sold by others 

I have noticed this recently

**Comment by hax0r31337** [comment]
> 「逃げたら一つ、進めば二つ」 said Suletta Mercury  

I'm gonna stepping forward and not giving up 🥰

**Comment by Wlenk** [comment]
> Your project is being sold by others

Lmao. This is ours project too. You like a kid.
Lmao

**Comment by hax0r31337** [comment]
> > Your project is being sold by others
> 
> 有没有可能 我也是ph官方的开发者

Please notice that this repository is **English only**, you may get banned if you continues speaking foreign language

**Comment by Wlenk** [comment]
> > > Your project is being sold by others
> > 
> > 
> > 有没有可能 我也是ph官方的开发者
> 
> Please notice that this repository is **English only**, you may get banned if you continues speaking foreign language

Edited

**Comment by hax0r31337** [comment]
Some of comments was deleted by original sender, I have recovered them and locked the conversation.
