### ISSUE TITLE
do you have a discord server?

### ISSUE THREAD

**Issue by YZSomething** [hax0r31337/ProtoHax-Android#27]

**Comment by YZSomething** [comment]
i need another help when i use protohax and try to join the hive it says "sorry we couldn't validate your login"

**Comment by hax0r31337** [comment]
no we do not have a discord server currently

**Comment by hax0r31337** [comment]
> i need another help when i use protohax and try to join the hive it says "sorry we couldn't validate your login"

make sure you have logged in a Microsoft account on ProtoHax and selected one, and have `Offline Session Override` which can be found in settings disabled
