### ISSUE TITLE
Cant drag

### ISSUE THREAD

**Issue by Muchonigir** [hax0r31337/ProtoHax-Android#30]
So basically i cant drag any shortcut or things meant to be draggable.This messes up the shortcut thing

**Comment by hax0r31337** [comment]
Can you do a screen record with "Show touches on screen" on?

**Comment by Muchonigir** [comment]
Alright

**Comment by Muchonigir** [comment]
Here wait trying to send

**Comment by Muchonigir** [comment]
https://github.com/hax0r31337/ProtoHax-Android/assets/128259578/9e8a8150-bb08-472f-a1ba-4517fe6b00b0

**Comment by Muchonigir** [comment]
https://github.com/hax0r31337/ProtoHax-Android/assets/128259578/247b26ff-e487-4896-8edd-80ff85dd1a22

**Comment by Muchonigir** [comment]
Uploading Recorder_23062023_200114.mp4…

**Comment by Muchonigir** [comment]
https://github.com/hax0r31337/ProtoHax-Android/assets/128259578/e3fcc5e4-d8c3-4697-b022-d7f5ed422d77

**Comment by hax0r31337** [comment]
Long press for 1 sec is required to drag, but I will improve dragable widgets
