### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by JaydenIsBaiting** [hax0r31337/ProtoHax-Android#36]
I can't join most servers idk if it's the VPN but I tried logging on the server first then using protohax but when I turned on the VPN and it disconnected me instantly (I could play before turning It on)

**Comment by hax0r31337** [comment]
have you logged in your MS account in ProtoHax?

**Comment by BrineModz** [comment]
I have the same issue, it keeps connecting and then time outs.

**Comment by JaydenIsBaiting** [comment]
> have you logged in your MS account in ProtoHax?

Yes I have

**Comment by hax0r31337** [comment]
duplicated with https://github.com/hax0r31337/ProtoHax/issues/28
