### ISSUE TITLE
I keep crashing 

### ISSUE THREAD

**Issue by GithubUset** [hax0r31337/ProtoHax-Android#39]
I didn't see the solution because u closed the issue before I read it and everytime when I click on account thingy and make my account it just says random stuff but doesn't let me log in and says 1/3 and becomes a white screen and whenever I try to select application it crashes

**Comment by hax0r31337** [comment]
just provide logs

**Comment by GithubUset** [comment]
u misunderstood me I just click select the application then it crashes there is no logs

**Comment by GithubUset** [comment]
I'm android 13

**Comment by LvzBxLzSyP** [comment]
> I'm android 13

Me too, when I select the app, as long as I reach the word starting with D, it will crash, but I can choose the app and log in at the same time, I am Android 13

**Comment by hax0r31337** [comment]
duplicated with #37
