### ISSUE TITLE
[BUG] Hive Join Bug

### ISSUE THREAD

**Issue by RohanDaCoder** [hax0r31337/ProtoHax-Android#42]
When trying to join the Hive Server. It stucks on "Connecting To External Server" But Sometimes Very Rarely, I can join the server but if you somehow disconnect   it won't let me join the server again..

Please Fix This Bug..
If This is fixable Please Let Us Know.

**Comment by hax0r31337** [comment]
It has been fixed in https://github.com/hax0r31337/ProtoHax/commit/0caeb7762c56075de14e82639583b952868ff76e

**Comment by RohanDaCoder** [comment]
> It has been fixed in [hax0r31337/ProtoHax@0caeb77](https://github.com/hax0r31337/ProtoHax/commit/0caeb7762c56075de14e82639583b952868ff76e)

how can i get the apk??
