### ISSUE TITLE
[BUG] when selecting an application it crashed

### ISSUE THREAD

**Issue by blob83** [hax0r31337/ProtoHax-Android#44]
**Describe the bug**

**To Reproduce**
1. Go to Protohax
2. Click on select application 
3. It crashed the application

**Expected behavior**
I thought it was going to work.

**Screenshots**
No screenshots but it was instant

**Please complete the following information:**
 - OS: [Android 12]
 - Version [ 1.3.3]

**Additional context**

**Comment by acsun124** [comment]
#37 duplicate
