### ISSUE TITLE
[BUG] Weird Error Messages While Joining The Hive.

### ISSUE THREAD

**Issue by RohanDaCoder** [hax0r31337/ProtoHax-Android#47]
When trying to join the hive, sometimes i get a weird error message.. The errors are: "Abagnale", "failed to connect"
I didn't have got these error messages in my life 💀 

Protohax Version: 1.4.0
Minecraft Version: 1.20.0.01
Device: Android 11, Vivo Y11

**Comment by hax0r31337** [comment]
unable to reproduce
