### ISSUE TITLE
[BUG] Can't open Minecraft server Java and Bedrock hosting

### ISSUE THREAD

**Issue by Khallev** [hax0r31337/ProtoHax-Android#48]
**Describe the bug**

**To Reproduce**
1. Go to 'Protohax And Connect it'
2. Click on 'Launch App'
3. Scroll down to 'Server'
4. See error and can't join Minecraft Java and Bedrock Hosting

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. Android 10]
 - Version [e.g. 1.3.3]

**Additional context**

**Comment by hax0r31337** [comment]
unable to reproduce
