### ISSUE TITLE
[BUG] TargetIndicator's HP Bar Does Not Work

### ISSUE THREAD

**Issue by RohanDaCoder** [hax0r31337/ProtoHax-Android#49]
The New TargetIndicator module's HP Bar Does Not Work.
It just be stuck at 20/20 while the target is damaged.

ProtoHax Version: 1.4.0
Minecraft Version: 1.20.0.01
Device: Android 11, Vivo Y11

**Comment by hax0r31337** [comment]
its a server-side, the server doesn't stream health of other players to your Minecraft client
