### ISSUE TITLE
[FEAT] 1.4.0-1 armv7 apk

### ISSUE THREAD

**Issue by RohanDaCoder** [hax0r31337/ProtoHax-Android#52]
Please Make a armv7 version of release 1.4.0-1

**Comment by mrkash69** [comment]
based 💀

**Comment by airport** [comment]
Majority of ProtoHax's userbase use a 32bit device - adding back the armv7 version won't hurt and is only going to increase the mod's popularity.

**Comment by hax0r31337** [comment]
These devices are too outdated to even play Minecraft with a playable frame rate, just get a new phone

**Comment by airport** [comment]
World's best selling phones are on 32bit OS despite being released in 2022 and 2023. Samsung A13 and A14 are on 32bit OS and are the phones that most people have and Minecraft works perfectly fine on it.

**Comment by hax0r31337** [comment]
> World's best selling phones are on 32bit OS despite being released in 2022 and 2023. Samsung A13 and A14 are on 32bit OS and are the phones that most people have and Minecraft works perfectly fine on it.

In fact samsung A13 and A14 supports armv8 actually

**Comment by mrkash69** [comment]
@hax0r31337 Not to rude but, is it that much of a hassle to make it 32-bit?
Yes 32-bit devices are slow but it seems unreasonable to just not support it out of the blue, considering only one patch ago had 32-bit support.
Does it _need_ to be 64-bit only?

**Comment by blob83** [comment]
I just realized you can use the 1.4.0 one and still works on 1.20.1
