### ISSUE TITLE
[BUG] unknown apk????

### ISSUE THREAD

**Issue by PhoenixxxxYT** [hax0r31337/ProtoHax-Android#53]
There is a bug or something else that when i download the apk its says unknown and i couldn't install it at all. I tried everything but its not working at all and its the latest update and also same with previous updates all are unknown. My phone is android 7 but its also not installing on Android 11. What should i do and keep in mind that my unknown apps(from google or any other link) installation option is turned on in settings.
Here i have screenshots
![Screenshot_20230714-000603](https://github.com/hax0r31337/ProtoHax-Android/assets/102614068/0cc80c8d-dd24-47aa-8061-af1ceb69ed82)

This is the unknown apk 

![Screenshot_20230714-000940](https://github.com/hax0r31337/ProtoHax-Android/assets/102614068/24effba0-92cc-43cb-8c7d-fbf4ff3f09d4)

Look others apps have their info below their name but not this one

![Screenshot_20230714-001124](https://github.com/hax0r31337/ProtoHax-Android/assets/102614068/80dd41f7-4f03-4c1d-a6b8-0fab8cdd493c)

I hope you will try to fix it
Regards. Thank you 😊

**Comment by mrkash69** [comment]
Your phone is probably 32 bit. You can try to download 1.4.0's armv7 (32bit) APK. Here is a link to it. https://github.com/hax0r31337/ProtoHax-Android/releases/download/v1.4.0/protohax-1.4.0-armv7.apk

**Comment by mrkash69** [comment]
Try re-downloading the APK.

**Comment by hax0r31337** [comment]
The minimal requirements of ProtoHax is Android 9 or above and a 64 bit cpu (armv8/x86_64)

**Comment by PhoenixxxxYT** [comment]
My phone is of 64bit and the armv7 apk is also not working :(
