### ISSUE TITLE
[BUG]The Miner feature does not work on some servers 

### ISSUE THREAD

**Issue by xTheW1ndx** [hax0r31337/ProtoHax-Android#56]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. Android 13]
 - Version [e.g. 1.3.2]

**Additional context**

**Comment by hax0r31337** [comment]
Can you tell me it doesn't work in **WHICH** server

**Comment by hax0r31337** [comment]
issue timed out
