### ISSUE TITLE
[BUG] Trying To Login Into a Account Throws An Error

### ISSUE THREAD

**Issue by RohanDaCoder** [hax0r31337/ProtoHax-Android#57]
**Describe the bug**
When Trying To Log In into an account it throws this error:

" java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator s5.r.iterator()' on a null object reference "

**To Reproduce**
1. Open ProtoHax
2. Go to Account Section
3. Click on the Plus button
4. Enter Credentials
5. See error

**Expected behavior**
Login To The Account Normally.

**Screenshots**
![Login Error](https://github.com/hax0r31337/ProtoHax-Android/assets/102975537/f077cf29-3780-4d3e-a27c-747445311a2b)

**Please complete the following information:**
 - OS: Android 11,  Vivo Y11
 - Version 1.4.0

**Comment by hax0r31337** [comment]
login your account in minecraft once
