### ISSUE TITLE
[BUG] account login error

### ISSUE THREAD

**Issue by uni4565** [hax0r31337/ProtoHax-Android#59]
I get an error when I try to log in to my account.

1. Go to Account
2. Click on +
3. Account Login

![Screenshot_2023-07-21-22-49-20-50_366db581b5e08226103095b2e8e463cd](https://github.com/hax0r31337/ProtoHax-Android/assets/109690187/d900fa3f-a5df-4aa9-b38e-7c1828c636e4)

 - OS: Android 10
 - Version 1.4.0-1

**Comment by hax0r31337** [comment]
login your account in minecraft once
