### ISSUE TITLE
Doesn't work properly on Android 13

### ISSUE THREAD

**Issue by Benedikt05** [hax0r31337/ProtoHax-Android#6]

**Comment by hax0r31337** [comment]
seems duplicate to #5

**Comment by Benedikt05** [comment]
Its not

**Comment by hax0r31337** [comment]
> Its not

can you describe which part is not working properly

**Comment by Benedikt05** [comment]
![Screenshot_20230129_153038_Minecraft](https://user-images.githubusercontent.com/60869945/215333588-d2bd4b01-30df-49ae-83af-6dbd8c7df298.jpg)

**Comment by Benedikt05** [comment]
"ProtoHax is not optimized for the latest Android version
Screen touches may or may not be delayed
recognized."
in addition, i cant join the proxy server

**Comment by hax0r31337** [comment]
> "ProtoHax is not optimized for the latest Android version Screen touches may or may not be delayed recognized." in addition, i cant join the proxy server

Which ROM are you using, it working on my MI 8 SE with PixelExperience 13
btw the issue causing unable to connect has been reported in #5, we are locating the issue

**Comment by Benedikt05** [comment]
> > "ProtoHax is not optimized for the latest Android version Screen touches may or may not be delayed recognized." in addition, i cant join the proxy server
> 
> Which ROM are you using, it working on my MI 8 SE with PixelExperience 13 btw the issue causing unable to connect has been reported in #5, we are locating the issue

It's a Samsung phone with Android 13, One UI 5

**Comment by Benedikt05** [comment]
@hax0r31337 do you have Discord?

**Comment by hax0r31337** [comment]
> @hax0r31337 do you have Discord?

yeah, what's yours

**Comment by Benedikt05** [comment]
> > @hax0r31337 do you have Discord?
> yeah, what's yours
Benedikt#9348
